apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: siredmar-system-upgrade-v1-5db45590-4356-4866-a0b0-a18e558f8292
  namespace: system-upgrade
spec:
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - {
          key: kubernetes.io/hostname,
          operator: In,
          values: ['jellyfish'],
        }
  serviceAccountName: system-upgrade
  drain:
    force: false
    disableEviction: true
  version: bar
  tolerations:
    - key: 'edgefarm.io'
      operator: 'Exists'
      effect: 'NoSchedule'
  upgrade:
    image: siredmar/system-upgrade:v1
    command: ['/entrypoint.sh']
    args: ['/tmp/concurrent', 'bar', '/tmp/successfile']
    volumes:
      - name: tmp
        source: /tmp
        destination: /tmp
