apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: acceleration-app
spec:
  components:
    - name: acceleration
      type: edgefarm-applications
      properties:
        image: ghcr.io/ci4rail/edgefarm-accel-demo-edgeapp/accel-samples:1.1.0
        nodepoolSelector:
          matchLabels:
            ac100a: ""
        name: acceleration
        
        cpu: 0.25
        memory: 256Mi
        
      traits:
        - type: edgefarm-network
          properties:
            network:
              name: acceleration-network
              subnetwork: colibri
              user: publish
        
