---
apiVersion: v1
kind: Secret
metadata:
  name: ubuntu-22-04-5bbe6-secret
  namespace: system-upgrade
type: Opaque
stringData:
  upgrade.sh: |
    #!/bin/sh
    set -e
    
    # package versions
    curl=7.58.0-2ubuntu3.14
    openssl=1.1.1-1ubuntu2.1~18.04.13
    
    # update package index
    apt-get --assume-yes update
    
    # install packages
    apt-get --assume-yes install \
      curl=$(curl) \
      libcurl4=$(curl) \
      libssl1.1=$(openssl) \
      openssl=$(openssl)
    
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: ubuntu-22-04-5bbe6
  namespace: system-upgrade
spec:
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - {
          key: kubernetes.io/hostname,
          operator: In,
          values: ['ac100a'],
        }
  serviceAccountName: system-upgrade
  secrets:
    - name: ubuntu-22-04-5bbe6-secret
      path: /host/run/system-upgrade/secrets/ubuntu
  version: "22.04"
  tolerations:
    - key: 'edgefarm.io'
      operator: 'Exists'
      effect: 'NoSchedule'
  upgrade:
    image: ubuntu:22.04
    command: ["chroot", "/host"]
    args: ["sh", "/run/system-upgrade/secrets/ubuntu/upgrade.sh"]

