apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: stress
spec:
  components:
    - name: stress
      type: edgefarm-applications
      properties:
        image: alexeiled/stress-ng:latest
        nodepoolSelector:
          matchLabels:
            jellyfish: ""
        name: stress
        
        cpu: 0.25
        memory: 256Mi
        
      traits:
        - type: edgefarm-network
          properties:
            network:
              name: a
              subnetwork: a
              user: a
        
