apiVersion: v1
kind: Node
metadata:
  labels:
    kubernetes.io/hostname: parrot
    openyurt.io/is-edge-worker: "true"
    apps.openyurt.io/desired-nodepool: parrot
  name: parrot
spec:
  taints:
    - effect: NoSchedule
      key: edgefarm.io
---
apiVersion: apps.openyurt.io/v1beta1
kind: NodePool
metadata:
  name: parrot
  labels:
    parrot: ""
    #monitor.edgefarm.io/metrics: default
spec:
  selector:
    matchLabels:
      apps.openyurt.io/nodepool: parrot
  type: Edge
