---
apiVersion: v1
kind: Secret
metadata:
  name: colibri-mender-v1-0-1f596-secret
  namespace: system-upgrade
type: Opaque
stringData:
  upgrade.sh: |
    #!/bin/sh
    set -e
    
    # update package index
    apt-get --assume-yes update
    
    # install packages
    apt-get --assume-yes install \
      htop
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: colibri-mender-v1-0-1f596
  namespace: system-upgrade
spec:
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - {
          key: kubernetes.io/hostname,
          operator: In,
          values: ['ac100a'],
        }
  serviceAccountName: system-upgrade
  secrets:
    - name: colibri-mender-v1-0-1f596-secret
      path: /host/run/system-upgrade/secrets/ubuntu
  drain:
    force: false
    disableEviction: true
  version: "v1.0"
  tolerations:
    - key: 'edgefarm.io'
      operator: 'Exists'
      effect: 'NoSchedule'
  upgrade:
    image: ubuntu
    command: ["chroot", "/host"]
    args: ["sh", "/run/system-upgrade/secrets/ubuntu/upgrade.sh"]

