apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: colibri-2
  annotations:
    'edgefarm.io/cluster': default
    'edgefarm.io/release-image': 'ci4rail/colibri-mender:v1.1'
spec:
  type: Release
  owner: default/batthebee
  lifecycle: production
  system: system:default/demo-colibri
