apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: myapplication
spec:
  components:
    - name: shell
      type: edgefarm-applications
      properties:
        image: alpine:latest
        nodepoolSelector:
          matchLabels:
            alpine: ""
        name: shell
        command:
            - sh
        args:
            - -c
            - "echo hello world && sleep 100000"
        cpu: 0.25
        memory: 256Mi
      traits:
        - type: edgefarm-network
          properties:
            network:
              name: mynetwork
              subnetwork: mysubnetwork
              user: myuser
        