apiVersion: v1
kind: Node
metadata:
  labels:
    kubernetes.io/hostname: colibri
    openyurt.io/is-edge-worker: 'true'
    apps.openyurt.io/desired-nodepool: colibri
  name: colibri
spec:
  taints:
    - effect: NoSchedule
      key: edgefarm.io
---
apiVersion: apps.openyurt.io/v1beta1
kind: NodePool
metadata:
  name: colibri
  labels:
    colibri: ""
spec:
  selector:
    matchLabels:
      apps.openyurt.io/nodepool: colibri
  type: Edge
