apiVersion: v1
kind: Node
metadata:
  labels:
    kubernetes.io/hostname: fwe
    openyurt.io/is-edge-worker: "true"
    apps.openyurt.io/desired-nodepool: fwe
  name: fwe
spec:
  taints:
    - effect: NoSchedule
      key: edgefarm.io
---
apiVersion: apps.openyurt.io/v1beta1
kind: NodePool
metadata:
  name: fwe
  labels:
    fwe: ""
    monitor.edgefarm.io/metrics: default
spec:
  selector:
    matchLabels:
      apps.openyurt.io/nodepool: fwe
  type: Edge
